#!/bin/bash

# You have to define DAILYBOT_PATH before running this script

APP="dailybot"
 
start() 
{
	cd $DAILYBOT_PATH
	$JAVA_HOME/bin/java -server -Xms32m -Xmx512m -jar  -Djava.security.policy=java.policy dailyBot_ec2.jar &
	echo $! > $DAILYBOT_PATH"dailybotpid"
}
 
stop() 
{
  kill -9 $(cat $DAILYBOT_PATH"dailybotpid")
}
 
case "$1" in
  start)
    echo "Starting $APP"
    start
    echo "$APP started."
    ;;
 
  stop)
    echo "Stopping $APP"
    stop
    echo "$APP stopped."
    ;;
 
  restart)
    echo  "Restarting $APP."
    stop
    sleep 2
    start
    echo "$APP restarted."
    ;;
  
  status)
    pgrep $(cat $DAILYBOT_PATH"dailybotpid")
    pgrep $(cat $DAILYBOT_PATH"dailybottestingpid")
    ;; 
 
  *)
    service_name=/etc/init.d/$APP
    echo "Usage: $service_name {start|stop|restart|status}" >&2
    exit 1
    ;;
esac
 
exit 0
