#!/bin/bash

# You have to define DAILYBOT_PATH before running this script

APP="dailybot"
 
start() 
{
	argument="-J-Djava.rmi.server.codebase=file://"
	argument=$argument$DAILYBOT_PATH
	argument=$argument"bin/"
	if pgrep "rmi";
	then
			echo "RMI running"
	else
			/usr/lib/jvm/java-7-oracle/bin/rmiregistry $argument &
			echo "RMI started $!"
	fi
	cd $DAILYBOT_PATH
	/usr/lib/jvm/java-7-oracle/bin/java -server -Xms256m -Xmx2048m -jar  -Djava.security.policy=java.policy dailyBot.jar &
	echo $! > $DAILYBOT_PATH"dailybotpid"
	/usr/lib/jvm/java-7-oracle/bin/java -server -Xms256m -Xmx2048m -jar  -Djava.security.policy=java.policy dailyBot.jar testing &
	echo $! > $DAILYBOT_PATH"dailybottestingpid"
}
 
stop() 
{
  kill -9 $(cat $DAILYBOT_PATH"dailybotpid")
  kill -9 $(cat $DAILYBOT_PATH"dailybottestingpid")
}
 
case "$1" in
  start)
    echo "Starting $APP"
    start
    echo "$APP started."
    ;;
 
  stop)
    echo "Stopping $APP"
    stop
    echo "$APP stopped."
    ;;
 
  restart)
    echo  "Restarting $APP."
    stop
    sleep 2
    start
    echo "$APP restarted."
    ;;
  
  status)
    pgrep $(cat $DAILYBOT_PATH"dailybotpid")
    pgrep $(cat $DAILYBOT_PATH"dailybottestingpid")
    ;; 
 
  *)
    service_name=/etc/init.d/$APP
    echo "Usage: $service_name {start|stop|restart|status}" >&2
    exit 1
    ;;
esac
 
exit 0
